apiVersion: v1
kind: Service
metadata:
  name: lab-b-web-service
spec:
  type: ClusterIP
  selector:
    app: lab-b-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP