spring.application.name=api-gateway-server
server.port=${SERVER_PORT:8080}

spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=posts
spring.cloud.gateway.routes[1].uri=${POST_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/post/**

spring.cloud.gateway.routes[2].id=comments
spring.cloud.gateway.routes[2].uri=${COMMENT_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/comment/**

management.server.port=${MANAGEMENT_PORT:9090}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
